import { afterAll, describe, expect, it } from 'vitest';
import { spawnSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { cleanupTempDirs, mkTempDir, mkYanHome, repoRoot } from '../helpers/fixtures.js';

/**
 * Phase 0 Trace, the two bullets about `bin/yan`:
 *
 *   - "Every existing `yan <cmd>` still works, unchanged, through the fallback"
 *   - "`yan --help` is generated by Commander and lists the same commands"
 *   - "`jq` is gone from `bin/yan`'s inline dependency check; `node` is there"
 *
 * The dispatcher is shell, so it is tested by running it, from bash, in a
 * throwaway `$YAN_HOME` — the same thing `tests/unit/yan-dispatch.test.sh` does
 * for the shell half. The two homes below are the two states that matter: one
 * that has never been built (a fresh clone) and one that has.
 */

afterAll(cleanupTempDirs);

function yan(home: string, args: readonly string[]): { code: number; out: string } {
  // YAN_HOME is unset on purpose: the dispatcher must resolve it from its own
  // location, which is how a copied fixture home stays self-contained.
  const env = { ...process.env };
  delete env.YAN_HOME;
  const r = spawnSync('bash', [join(home, 'bin', 'yan'), ...args], {
    encoding: 'utf8',
    env,
    windowsHide: true,
  });
  return { code: r.status ?? 1, out: `${r.stdout ?? ''}${r.stderr ?? ''}` };
}

function addShellCommand(home: string, name: string, body: string): void {
  const file = join(home, 'bin', `yan-${name}.sh`);
  writeFileSync(file, `#!/usr/bin/env bash\n${body}\n`);
  chmodSync(file, 0o755);
}

describe('bin/yan, in a tree that has never been built', () => {
  const home = mkYanHome(mkTempDir());

  it('prints the derived command list and exits 0', () => {
    for (const form of ['--help', '-h', 'help']) {
      const r = yan(home, [form]);
      expect(r.code, form).toBe(0);
      expect(r.out).toContain('usage: yan');
      expect(r.out).toContain('doctor');
    }
    const bare = yan(home, []);
    expect(bare.code).toBe(0);
    expect(bare.out).toContain('doctor');
  });

  it('refuses an unknown command', () => {
    const r = yan(home, ['bogus']);
    expect(r.code).not.toBe(0);
    expect(r.out).toContain('unknown command: bogus');
  });

  it('dispatches one-word and two-word commands to the shell half', () => {
    addShellCommand(home, 'fake', `printf 'one-word|%s|home=%s\\n' "$*" "\${YAN_HOME:-unset}"`);
    addShellCommand(home, 'fake-sub', `printf 'two-word|%s\\n' "$*"`);

    expect(yan(home, ['fake', 'sub', 'alpha', 'beta']).out).toContain('two-word|alpha beta');
    expect(yan(home, ['fake-sub', 'alpha']).out).toContain('two-word|alpha');
    expect(yan(home, ['fake', 'other']).out).toContain('one-word|other');
    // YAN_HOME is exported to the subcommand and points at this home. The
    // comparison is on the last segment, not the whole path: bash says
    // /tmp/yan-test-X and Node says C:\Users\…\Temp\yan-test-X, and that gap is
    // an MSYS *mount point*, which normalizePath() cannot close — it translates
    // drive letters (/c/… → C:/…), not the mount table. Nothing yan builds
    // lives outside $YAN_HOME, so this only ever bites a test.
    const printed = /home=(\S+)/.exec(yan(home, ['fake']).out)?.[1] ?? '';
    expect(printed.endsWith(basename(home))).toBe(true);
  });
});

describe('bin/yan, in a built tree', () => {
  const home = mkYanHome(mkTempDir(), { withDist: true });

  it('has a dist to dispatch into', () => {
    expect(existsSync(join(home, 'dist', 'cli', 'yan.js'))).toBe(true);
  });

  it('generates help from Commander and lists the same commands', () => {
    const r = yan(home, ['--help']);
    expect(r.code).toBe(0);
    // Commander's own layout...
    expect(r.out).toContain('Usage: yan');
    // ...listing the shell half it has not taken over yet.
    for (const name of ['doctor', 'ls', 'session-start', 'shift', 'wait']) {
      expect(r.out, name).toContain(name);
    }
  });

  it('reports a version', () => {
    const r = yan(home, ['--version']);
    expect(r.code).toBe(0);
    expect(r.out).toContain('yan ');
  });

  it('still reaches the shell half for a command that has not been ported', () => {
    addShellCommand(home, 'echoer', `printf 'shell-half|%s\\n' "$*"`);
    const r = yan(home, ['echoer', 'hello']);
    expect(r.code).toBe(0);
    expect(r.out).toContain('shell-half|hello');
  });

  it('prefers the ported half wherever both exist', () => {
    // Two implementations of the same name. The marker `bin/yan` looks at is
    // `dist/cli/<name>.js`, and the compiled root must agree with it, or a
    // ported command would be announced and never run.
    addShellCommand(home, 'both', `printf 'shell-half\\n'`);
    mkdirSync(join(home, 'dist', 'cli'), { recursive: true });
    writeFileSync(
      join(home, 'dist', 'cli', 'both.js'),
      [
        `import { Command } from 'commander';`,
        `export const command = new Command('both')`,
        `  .description('a ported command')`,
        `  .action(() => { process.stdout.write('ported-half\\n'); });`,
        '',
      ].join('\n'),
    );

    const r = yan(home, ['both']);
    expect(r.code).toBe(0);
    expect(r.out).toContain('ported-half');
    expect(r.out).not.toContain('shell-half');
  });
});

describe('the inline dependency check', () => {
  const source = readFileSync(join(repoRoot, 'bin', 'yan'), 'utf8');

  it('asks for git and node, and no longer for jq', () => {
    const line = /for _yan_dep in ([^;]+); do/.exec(source);
    expect(line).not.toBeNull();
    const deps = (line?.[1] ?? '').trim().split(/\s+/);
    expect(deps).toEqual(['git', 'node']);
  });

  it('keeps no central list of subcommands', () => {
    expect(/^[ \t]*(doctor|repo-add|shift)\)/m.test(source)).toBe(false);
  });
});
